
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: 6.0.x
      publish-on-failed-tests:
        required: false
        type: boolean
        default: false

    secrets:
      CODECOV_TOKEN:
        required: false
      NUGET_TOKEN:
        required: true
      DISCORD_WEBHOOK:
        required: false

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Secrets can't be referenced in conditionals, but environment variables can.
    # Workaround for https://github.com/github/docs/pull/12722
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Run tests
        run: dotnet test --configuration Release --logger "GitHubActions;report-warnings=false"

      - name: Upload coverage
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && (success() || inputs.publish-on-failed-tests) }}
    needs: test
    runs-on: windows-latest

    # Secrets can't be referenced in conditionals, but environment variables can.
    # Workaround for https://github.com/github/docs/pull/12722
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Get release version
        id: get-version
        uses: dawidd6/action-get-tag@v1

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Deploy
        run: dotnet nuget push **\*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}

      - name: Notify Discord
        if: ${{ env.DISCORD_WEBHOOK }}
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**${{ github.event.repository.name }}** new version released!\nVersion: `${{ steps.get-version.outputs.tag }}`\nChangelog: <https://github.com/${{ github.event.repository.full_name }}/blob/${{ steps.get-version.outputs.tag }}/Changelog.md>"
            }
