on:
  workflow_call:
    inputs:
      windows-only:
        type: boolean
        required: false
        default: false
      skip-tests:
        type: boolean
        required: false
        default: false
      deploy:
        type: boolean
        required: true
      package-version:
        type: string
        required: true
      dotnet-version:
        type: string
        required: false
      dotnet-test-logger:
        type: string
        required: false
        default: GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true

    secrets:
      CODECOV_TOKEN:
        required: false
      NUGET_TOKEN:
        required: true
      DISCORD_WEBHOOK:
        required: false

env:
  TERM: xterm
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  format:
    runs-on: ${{ inputs.windows-only && 'windows-latest' || 'ubuntu-latest' }}
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      # This currently relies on an assumption that the build runs the formatting task implicitly,
      # which is the case for CSharpier, but not necessarily for other formatting tools.
      - name: Verify formatting
        run: dotnet build --configuration Release

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        exclude:
          # Exclude non-Windows jobs if necessary
          - os: ${{ inputs.windows-only && 'ubuntu-latest' }}
          - os: ${{ inputs.windows-only && 'macos-latest' }}

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    permissions:
      contents: read

    env:
      # Secrets can't be referenced in conditionals, but environment variables can.
      # https://github.com/github/docs/issues/6861#issuecomment-870757186
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Run tests
        # Skip tests here instead of the whole job to ensure the dependant jobs still run
        if: ${{ !inputs.skip-tests }}
        run: >
          dotnet test
          -p:CSharpier_Bypass=true
          --configuration Release
          --logger "${{ inputs.dotnet-test-logger }}"
          --collect:"XPlat Code Coverage"
          --
          RunConfiguration.CollectSourceInformation=true
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload coverage
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pack:
    runs-on: ${{ inputs.windows-only && 'windows-latest' || 'ubuntu-latest' }}
    timeout-minutes: 10

    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Create packages
        run: >
          dotnet pack
          -p:Version=${{ inputs.package-version }}
          -p:CSharpier_Bypass=true
          -p:ContinuousIntegrationBuild=true
          -p:PublishRepositoryUrl=true
          -p:EmbedUntrackedSources=true
          -p:DebugType=embedded
          --configuration Release

      - name: Upload packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages
          path: "**/*.nupkg"
          if-no-files-found: error

  deploy:
    if: ${{ inputs.deploy }}

    needs:
      - format
      - test
      - pack

    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: packages

      - name: Create release
        # Untagged deployments (e.g. from workflow_dispatch) don't need a full release
        if: ${{ github.ref_type == 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ github.ref_name }}
          $(find . -type f -wholename **/*.nupkg -exec echo {} \; | tr '\n' ' ')
          --repo ${{ github.event.repository.full_name }}
          --title ${{ github.ref_name }}
          --generate-notes
          --verify-tag

      - name: Push packages
        run: >
          dotnet nuget push **/*.nupkg
          --source "https://api.nuget.org/v3/index.json"
          --api-key ${{ secrets.NUGET_TOKEN }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    env:
      # Secrets can't be referenced in conditionals, but environment variables can.
      # https://github.com/github/docs/issues/6861#issuecomment-870757186
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get favicon URL
        id: favicon
        run: |
          if [ -f favicon.png ]; then
            echo "url=https://raw.githubusercontent.com/${{ github.event.repository.full_name }}/${{ github.sha }}/favicon.png" >> "$GITHUB_OUTPUT"
          fi

      - name: Notify Discord
        if: ${{ env.DISCORD_WEBHOOK }}
        uses: tyrrrz/action-http-request@110f1a0f0f7e91c3b2de349539249f4573c243fa # 1.1.5
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            Content-Type: application/json; charset=UTF-8
          body: |
            {
              ${{ steps.favicon.outputs.url && format('"avatar_url": "{0}",', steps.favicon.outputs.url) || '' }}
              "content": "[**${{ github.event.repository.name }}**](<${{ github.event.repository.html_url }}>) v${{ inputs.package-version }} has been released!"
            }
          retry-count: 5
