on:
  workflow_call:
    inputs:
      windows-only:
        type: boolean
        required: false
        default: false
      deploy-on-tags-only:
        type: boolean
        required: false
        default: true
      dotnet-version:
        type: string
        required: false
      dotnet-test-logger:
        type: string
        required: false
        default: GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true
      package-version:
        type: string
        required: false

    secrets:
      CODECOV_TOKEN:
        required: false
      NUGET_TOKEN:
        required: true
      DISCORD_WEBHOOK:
        required: false

env:
  TERM: xterm
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        # Below is a hacky way to implement a conditional matrix
        windows-only:
          - ${{ inputs.windows-only }}
        exclude:
          - windows-only: true
            os: "ubuntu-latest"
          - windows-only: true
            os: "macos-latest"

    # Explicit name is required due to the matrix hack above
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    env:
      # Secrets can't be referenced in conditionals, but environment variables can.
      # https://github.com/github/docs/issues/6861#issuecomment-870757186
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # 4.1.0

      - name: Install .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # 3.2.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Run tests
        run: >
          dotnet test
          --configuration Release
          --logger "${{ inputs.dotnet-test-logger }}"
          --collect:"XPlat Code Coverage"
          --
          RunConfiguration.CollectSourceInformation=true
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload coverage
        if: ${{ env.CODECOV_TOKEN }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # 3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pack:
    runs-on: ${{ inputs.windows-only && 'windows-latest' || 'ubuntu-latest' }}
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # 4.1.0

      - name: Install .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # 3.2.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Create packages
        run: >
          dotnet pack
          --configuration Release
          -p:ContinuousIntegrationBuild=true
          ${{ inputs.package-version && format('-p:Version={0}', inputs.package-version) || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # 3.1.3
        with:
          name: packages
          path: "**/*.nupkg"

  deploy:
    if: ${{ !inputs.deploy-on-tags-only || github.event_name == 'push' && github.ref_type == 'tag' }}

    needs:
      - test
      - pack

    runs-on: ${{ inputs.windows-only && 'windows-latest' || 'ubuntu-latest' }}
    permissions:
      actions: read

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # 3.2.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Download artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # 3.0.2
        with:
          name: packages

      - name: Push packages
        run: >
          dotnet nuget push **/*.nupkg
          --source "https://api.nuget.org/v3/index.json"
          --api-key ${{ secrets.NUGET_TOKEN }}

  notify:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    needs: deploy
    runs-on: ${{ inputs.windows-only && 'windows-latest' || 'ubuntu-latest' }}

    env:
      # Secrets can't be referenced in conditionals, but environment variables can.
      # https://github.com/github/docs/issues/6861#issuecomment-870757186
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Notify Discord
        if: ${{ env.DISCORD_WEBHOOK }}
        uses: tyrrrz/action-http-request@64c70c67f5ebc54d4c7ea09cbe3553322778afd5 # 1.1.2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            Content-Type: application/json; charset=UTF-8
          body: |
            {
              "content": "**${{ github.event.repository.name }}** v${{ github.ref_name }} has been released!\n🔗 [Changelog](<${{ github.event.repository.html_url }}/blob/${{ github.ref_name }}/Changelog.md>)"
            }
          retry-count: 5
